# Generated by Django 4.2.7 on 2023-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_senior_list_proof_of_claiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_list',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
