# Generated by Django 4.2.7 on 2023-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_senior_list_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_list',
            name='allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='senior_list',
            name='allowance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
