# Generated by Django 4.2.7 on 2023-11-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_senior_list_sex_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
