# Generated by Django 4.2.7 on 2023-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_senior_list_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior_list',
            name='allowance_type',
            field=models.CharField(blank=True, choices=[('none', 'Select Type of Allowance'), ('monthly', 'Monthly Monetary Allowance')], max_length=50, null=True),
        ),
    ]
