# Generated by Django 4.2.7 on 2023-11-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_senior_list_allowance_type'),
        ('base', '0012_delete_customuser'),
    ]

    operations = [
    ]
