# Generated by Django 4.2.7 on 2023-11-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_list',
            name='active_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
