# Generated by Django 4.2.7 on 2023-11-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_senior_list_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senior_list',
            name='active_status',
        ),
    ]
