# Generated by Django 4.2.7 on 2023-11-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_senior_list_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_list',
            name='active_status',
            field=models.CharField(default='active', max_length=20, null=True),
        ),
    ]
