# Generated by Django 4.2.7 on 2023-11-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_merge_20231126_1522'),
        ('base', '0015_senior_list_active_status'),
    ]

    operations = [
    ]
