# Generated by Django 4.2.7 on 2023-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_senior_list_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senior_list',
            name='active_status',
        ),
        migrations.AddField(
            model_name='senior_list',
            name='allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='senior_list',
            name='allowance_type',
            field=models.CharField(blank=True, choices=[('none', 'Select Type of Allowance'), ('Monthly Monetary Allowance', 'Monthly Monetary Allowance')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='senior_list',
            name='date_of_deletion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senior_list',
            name='deletion_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
