# Generated by Django 4.2.7 on 2023-11-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_senior_list_active_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_list',
            name='date_of_deletion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
